### ISSUE TITLE
Morning code review

### ISSUE THREAD

**Issue by aliabbani** [ZeenatLawal/Leaderboard#2]
Good job so far 🥇!

There are some issues that you still need to work on but you are almost there 🎖️💇!

Add ♻️

- We suggest update the readme file and add a deployment link for the project.
- We think you can practice KISS JS practice. It is an optional change that you can have your DOM manipulation in a separate js file. 💅

Cheers and Happy coding!👏👏👏

Feel free to leave ask questions if something is not 100% clear.

**Comment by ZeenatLawal** [comment]
Thank you 😄
